package pluginapi

import (
	"context"
	"html/template"
)

// ContentBlock is a live fragment a plugin publishes for embedding in
// editor-authored content.
//
// The problem it solves: a site wants a catalogue page — every achievement and
// what it takes to earn one — with an editorial introduction around it. Writing
// that table by hand means it is wrong the first time somebody adds an
// achievement, and nobody notices because a wiki page has no reason to look
// stale. Generating a whole page instead loses the prose.
//
// So the page stays hand-written and the TABLE is a token:
//
//	Earning badges on this site is straightforward.
//
//	{{achievements}}
//
//	Ask a mod if you think one is scored wrongly.
//
// The wiki plugin expands `{{name}}` against whatever is registered under
// ContentBlockPrefix+name. An unregistered token is left alone as literal text
// rather than erased — a typo should be visible to the editor who made it, and
// silently deleting part of someone's page is worse than showing them the
// mistake.
//
// SANITISATION ORDER IS LOAD-BEARING. Editor content goes through markdown and
// then a sanitiser; expansion happens AFTER both. Two reasons, and they point
// the same way:
//
//   - A block's HTML is generated by a plugin, not typed by a person. It is
//     trusted for the same reason a template is. Passing it through the
//     sanitiser would strip the table markup it exists to produce.
//   - The token itself is inert text until expansion, so nothing an editor can
//     type reaches the expander as markup. An editor who writes
//     `{{achievements}}` inside a code fence gets the literal string, because by
//     then the sanitised HTML has it as escaped text in a <code> element and the
//     expander only replaces its own exact token form.
//
// Which means: a ContentBlock implementation must NEVER interpolate
// user-supplied text into its output without escaping it. It is writing HTML
// that nothing downstream will clean up.
type ContentBlock interface {
	// Render returns the fragment. An error leaves the token in place and is
	// logged — a page that renders with one block missing beats a 500 on the
	// help page.
	Render(ctx context.Context) (template.HTML, error)
}

// ContentBlockPrefix + a block name is its registry key, following
// rewards.metrics.* : a plugin registers "content.block.achievements" and the
// wiki resolves the token `{{achievements}}` to it without either side knowing
// the other exists.
const ContentBlockPrefix = "content.block."

// ContentBlockFunc adapts a plain function to ContentBlock.
type ContentBlockFunc func(ctx context.Context) (template.HTML, error)

func (f ContentBlockFunc) Render(ctx context.Context) (template.HTML, error) { return f(ctx) }

// ContentBlockKey returns the registry key for a block name.
func ContentBlockKey(name string) string { return ContentBlockPrefix + name }
