-- magic: torrent promotions ("buffs"), cast by members for points.

-- Operator knobs.
CREATE TABLE IF NOT EXISTS settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- The buff vocabulary — the classic promotions plus whatever the operator
-- adds. Ratios are CREDIT multipliers: up 2 / down 0 is 2×Free.
CREATE TABLE IF NOT EXISTS buff_defs (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug     TEXT NOT NULL UNIQUE,
    name     TEXT NOT NULL,
    up_ratio   DOUBLE PRECISION NOT NULL,
    down_ratio DOUBLE PRECISION NOT NULL,
    ordinal  INT NOT NULL DEFAULT 0,
    enabled  BOOLEAN NOT NULL DEFAULT TRUE
);

-- Every cast, forever — the history IS the log, and a promotion cannot be
-- edited once cast, only terminated by an admin (terminated_at stamps it,
-- the row stays).
CREATE TABLE IF NOT EXISTS magics (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caster_id     BIGINT NOT NULL,
    info_hash     CHAR(40) NOT NULL,
    -- scope: who the promotion applies to. 'all' every member, 'self' the
    -- caster alone (a private buff), 'user' the named target.
    scope         TEXT NOT NULL,
    target_user_id BIGINT,
    up_ratio      DOUBLE PRECISION NOT NULL,
    down_ratio    DOUBLE PRECISION NOT NULL,
    starts_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    ends_at       TIMESTAMPTZ NOT NULL,
    hours         INT NOT NULL,
    cost          BIGINT NOT NULL,
    comment       TEXT NOT NULL DEFAULT '',
    terminated_at TIMESTAMPTZ,
    terminated_by BIGINT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- The announce path's read: active magics on one torrent.
CREATE INDEX IF NOT EXISTS magics_active_idx
    ON magics (info_hash, ends_at) WHERE terminated_at IS NULL;

-- Casting experience: spend points on magic, get better at magic.
CREATE TABLE IF NOT EXISTS magic_xp (
    user_id BIGINT PRIMARY KEY,
    xp      BIGINT NOT NULL DEFAULT 0
);
