-- medals: the display cabinet.

-- The catalogue. price 0 means "not for sale" — grant-only, paid by rewards
-- or an admin. bonus_pct MAY be zero, and usually is: whether a medal does
-- anything besides being a medal is the host's decision (see
-- pluginapi.MedalBonusName).
CREATE TABLE IF NOT EXISTS medals (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug             TEXT NOT NULL UNIQUE,
    name             TEXT NOT NULL,
    icon             TEXT NOT NULL DEFAULT '',
    -- description_slug names a host message-catalogue entry, resolved per
    -- viewer through the medals.l10n seams; description is the fallback.
    description      TEXT NOT NULL DEFAULT '',
    description_slug TEXT NOT NULL DEFAULT '',
    bonus_pct        INT  NOT NULL DEFAULT 0,
    price            BIGINT NOT NULL DEFAULT 0,
    ordinal          INT  NOT NULL DEFAULT 0,
    enabled          BOOLEAN NOT NULL DEFAULT TRUE
);

-- Who holds what, and whether they are wearing it.
CREATE TABLE IF NOT EXISTS user_medals (
    medal_id    BIGINT NOT NULL REFERENCES medals(id) ON DELETE CASCADE,
    user_id     BIGINT NOT NULL,
    shown       BOOLEAN NOT NULL DEFAULT TRUE,
    acquired_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (medal_id, user_id)
);
CREATE INDEX IF NOT EXISTS user_medals_user_idx ON user_medals (user_id);
