-- games: community point games — the Pot and Charity.

-- Operator knobs, key/value like every plugin settings table.
CREATE TABLE IF NOT EXISTS settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- One pot cycle: fills toward target, closes with a winner, the next opens.
-- total is maintained beside the donation rows so the hot read (the progress
-- bar) is one indexed row, and the close check needs no sum.
CREATE TABLE IF NOT EXISTS pot_cycles (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target         BIGINT NOT NULL,
    total          BIGINT NOT NULL DEFAULT 0,
    started_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at       TIMESTAMPTZ,
    winner_user_id BIGINT,
    winner_points  BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS pot_cycles_open_idx ON pot_cycles (id) WHERE ended_at IS NULL;

-- One row per member per day per cycle: the daily-cap check and the
-- contributor totals both read straight off the primary key.
CREATE TABLE IF NOT EXISTS pot_donations (
    cycle_id BIGINT NOT NULL REFERENCES pot_cycles(id) ON DELETE CASCADE,
    user_id  BIGINT NOT NULL,
    day      DATE   NOT NULL DEFAULT CURRENT_DATE,
    amount   BIGINT NOT NULL,
    PRIMARY KEY (cycle_id, user_id, day)
);

-- The charity audit: who gave how much to how many. Recipients are NOT
-- listed by name anywhere — the gift is anonymous in both directions by
-- design — but the operator can still see the system is used.
CREATE TABLE IF NOT EXISTS charity_gifts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_id   BIGINT NOT NULL,
    amount     BIGINT NOT NULL,
    ratio_max  DOUBLE PRECISION NOT NULL,
    recipients INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
